apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"       # 0.5 CPU
              memory: "256Mi"   # 256 MiB
            limits:
              cpu: "1"          # 1 CPU
              memory: "512Mi"   # 512 MiB